### ISSUE TITLE
Broken docker compose on MacOS

### ISSUE THREAD

**Issue by zwobill** [arextest/deployments#3]
I am getting the following error with docker compose.

`Error response from daemon: error while creating mount source path '/Users/xxx/src/arex/deployments/arex-data/redis': chown /Users/xxx/src/arex/deployments/arex-data/redis: permission denied`

**Comment by haibing-wang** [comment]
This is a docker-compose  privilege problem. I'll fix it as soon as possible.

**Comment by mengqcc** [comment]
Mac M1: Mysql 5.7 does not have Linux /arm64/ V8 image, update to 8.0 and run successfully

**Comment by haibing-wang** [comment]
I updated the mysql version from 5.7 to mysql 8.0.29  in docker-compose.yml , and then the test passed.

**Comment by haibing-wang** [comment]
fixed and close the issue.
