### ISSUE TITLE
0caseCount

### ISSUE THREAD

**Issue by zaksyjm** [arextest/deployments#5]
前置条件：
1，docker-compose up -d中的yml文件，把mongo的版本号从5.0改成了4.4.4（5.0报错WARNING: MongoDB 5.0+ requires a CPU with AVX support）
2，agent的jar包与被测服务的jar放在同一个服务器内
3，配置选用设置conf文件方式
4，因为拉取的agent目录同时存在agent与bootstrap两个jar，没有动他们的位置

步骤：
1，先启动前端，确认成功进入主页面
2，后拉起被测服务
3，调用被测服务中的接口，以达到record目的
4，repaly，输入被测服务的ip与port

预期结果：调用完以后，页面上的caseCount个数增加，并且能够repaly
实际结果：调用完以后，页面上的caseCount个数仍然为0，并repaly时报错
<img width="385" alt="image" src="https://user-images.githubusercontent.com/110372205/182613720-a9e6151e-13bd-43a5-ae5d-f64a5fa0e16e.png">

conf文件配置项：
arex.service.name=yourAppName
arex.storage.service.host=127.0.0.1:8093
arex.config.service.host=127.0.0.1:8091

启动命令：
nohup java -javaagent:/mnt/AREX/deployments/agent/arex-agent-0.0.1.jar  -Darex.enable.debug=true -Darex.config.path=/home/cloud/arex.agent.conf  -jar -Xms128m -Xmx128m xxx.jar --qa.host=xxx --spring.profiles.active=dev >/dev/null 2>&1 &

额外信息：
启动日志：
<img width="1588" alt="image" src="https://user-images.githubusercontent.com/110372205/182614283-ac1cc5ab-8b0c-4810-afcf-45a59f5f2df4.png">

请求日志：
![image](https://user-images.githubusercontent.com/110372205/182615720-9b87fa1d-45bd-461a-8d37-22a26f7536a2.png)

**Comment by haibing-wang** [comment]
arex-schedule-service: add new config
==>
    environment:
      - "JAVA_OPTS=-Darex.storage.service.api=http://arex-storage-service:8080 -Darex.report.service.api=http://arex-report-service:8080 -Darex.config.service.api=http://arex-config-service:8080 -Dspring.datasource.url=jdbc:mysql://mysql:3306/arexdb -Dspring.datasource.username=arex_admin -Dspring.datasource.password=arex_admin_password"

**Comment by haibing-wang** [comment]
we add the java_ops option config in v0.2 version

**Comment by haibing-wang** [comment]
Detected on version 0.2.5, this problem has been fixed
