### ISSUE TITLE
k8s机器上部署，提示异常，导致部署失败

### ISSUE THREAD

**Issue by liaolongfei** [arextest/deployments#9]
部署失败，提示：
WARNING: MongoDB 5.0+ requires a CPU with AVX support, and your current system does not appear to have that!

**Comment by liaolongfei** [comment]
![image](https://user-images.githubusercontent.com/6407371/185051303-5df40d12-83ad-4a08-aac8-105be8598148.png)
将mongodb版本降为4.4.6即可

**Comment by haibing-wang** [comment]
[docker-compose-mongo4.4.21.yml](https://github.com/arextest/deployments/blob/main/docker-compose-mongo4.4.21.yml)
docker compose for mongo 4.4.21
helm Chart, update the mongodb version
